stages:
  - test

jobs:
  include:
    - stage: test
      python: "3.6"
      install:
        - pip install -r requirements.txt -r test_requirements.txt
      script:
        - prospector
        - pytest
      after_success:
        - codecov
