language: python

stages:
- test
- deploy

jobs:
  include:

  - stage: test
    python:
    - '3.5'
    - '3.6'
    install:
    - pip install -r requirements.txt -r test_requirements.txt
    script:
    - prospector
    - pytest -v
    after_success:
    - codecov
